# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'closed'), (3, 'spam')])),
                ('message', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('from_name', models.CharField(max_length=50)),
                ('from_id', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('buyer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('from_name', models.CharField(max_length=50)),
                ('from_id', models.CharField(max_length=50)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.Issue')),
            ],
        ),
    ]
