# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'closed'), (3, 'archived')]),
        ),
    ]
