# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20171029_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='from_id',
        ),
    ]
