# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_auto_20171029_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'closed'), (3, 'archived')], null=True),
        ),
    ]
